[package]
name = "monistode-macros"
version = "0.1.2"
edition = "2021"
description = "A set of assembler-generating macros for monistode"
license = "MIT"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"
monistode-binutils = "0.1.2"

[lib]
proc-macro = true
